-- migrations/041_cfo_issues.sql
-- Proactive anomaly detection — issues the CFO agent surfaces.
-- Daily/weekly emails read the top 3 critical. Dashboard shows the full list.
--
-- Each issue is generated by a specific detector rule, classified by severity,
-- and can be snoozed/resolved by Drew.

CREATE TABLE IF NOT EXISTS cfo_issues (
  id              TEXT PRIMARY KEY,
  detected_at     TEXT NOT NULL DEFAULT (datetime('now')),
  issue_type      TEXT NOT NULL,                -- 'vendor_anomaly' | 'margin_drift' | 'ar_aging_slip' | 'cash_trajectory' | 'customer_concentration' | 'vendor_concentration' | 'pipeline_depth' | 'unusual_transaction'
  severity        TEXT NOT NULL,                -- 'critical' | 'high' | 'medium' | 'low'
  subject         TEXT,                         -- entity this is about (vendor name, customer, etc.)
  headline        TEXT NOT NULL,                -- one-sentence summary for emails/dashboard
  detail          TEXT,                         -- longer explanation
  data_json       TEXT,                         -- structured data (current vs prior, threshold, etc.)
  suggested_action TEXT,
  status          TEXT NOT NULL DEFAULT 'open', -- 'open' | 'snoozed' | 'resolved' | 'dismissed'
  snooze_until    TEXT,
  resolved_at     TEXT,
  resolved_note   TEXT
);
CREATE INDEX IF NOT EXISTS idx_cfo_issues_status_severity ON cfo_issues(status, severity, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_cfo_issues_type_subject ON cfo_issues(issue_type, subject);
