#!/usr/bin/env node
// scripts/regen-readme.js
// Tier 6 — regenerate the README's "Workers" + "Cron schedule" sections from
// wrangler.toml + workers/ directory truth. Run after adding a new worker or
// changing a cron trigger:
//
//   node scripts/regen-readme.js
//
// Replaces everything between <!-- WORKERS:START --> and <!-- WORKERS:END -->
// (and the same for CRONS) so the rest of the README stays editable.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = dirname(__dirname);

// ── Worker categories — grouped for readability in README. Anything we don't
//    explicitly tag falls into "Other". Order matters; first match wins.
const WORKER_GROUPS = [
  { label: 'Core router + dispatch', match: ['router.js', 'orchestrator.js'] },
  { label: 'Wholesale pipeline', match: ['scout-worker.js', 'qualifier-worker.js', 'outreach-agent.js', 'outreach-workflow.js', 'account-worker.js', 'optimizer-worker.js', 'pilot-tracker-worker.js', 'rep-enablement-worker.js', 'reply-detector-worker.js', 'reply-handler-worker.js', 'approval-mailer.js'] },
  { label: 'Retail (SMS marketing)', match: ['retail-agent.js', 'retail-backfill-workflow.js', 'square-sync-worker.js'] },
  { label: 'Catering', match: ['catering-agent.js', 'catering-scout.js', 'catering-crossover-scout.js'] },
  { label: 'CFO / Finance (15 modules)', match: (n) => n.startsWith('finance-') || n === 'cfo-agent.js' || n === 'cfo-pulse-worker.js' || n === 'mercury-client.js' || n === 'qbo-client.js' || n === 'qbo-webhook-worker.js' },
  { label: 'Coach / Chat', match: ['coach-agent.js', 'chat-worker.js', 'chat-session-do.js', 'brain-loader.js'] },
  { label: 'Shared utilities', match: ['http-utils.js'] },
];

function buildWorkerSection() {
  const all = readdirSync(join(REPO, 'workers')).filter(f => f.endsWith('.js')).sort();
  const buckets = WORKER_GROUPS.map(g => ({ ...g, files: [] }));
  const orphan = [];
  for (const file of all) {
    let placed = false;
    for (const b of buckets) {
      const matches = typeof b.match === 'function' ? b.match(file) : b.match.includes(file);
      if (matches) { b.files.push(file); placed = true; break; }
    }
    if (!placed) orphan.push(file);
  }
  if (orphan.length) buckets.push({ label: 'Other / unclassified', files: orphan });

  const lines = [`<!-- Auto-generated by scripts/regen-readme.js — do not edit by hand -->`, ``];
  lines.push(`Total: **${all.length} worker modules**`);
  lines.push(``);
  for (const b of buckets) {
    if (!b.files.length) continue;
    lines.push(`### ${b.label} (${b.files.length})`);
    for (const f of b.files) lines.push(`- \`workers/${f}\``);
    lines.push(``);
  }
  return lines.join('\n');
}

function buildCronSection() {
  const toml = readFileSync(join(REPO, 'wrangler.toml'), 'utf8');
  // Pull every line inside the [triggers] crons = [...] block. Each line has the
  // pattern: `  "0 4 * * 7",       # CFO:        Sunday   10pm MT (...)`
  const cronLines = [];
  const inBlock = { val: false };
  for (const raw of toml.split('\n')) {
    const line = raw.trim();
    if (line.startsWith('crons = [')) { inBlock.val = true; continue; }
    if (inBlock.val && line.startsWith(']')) { inBlock.val = false; break; }
    if (!inBlock.val) continue;
    const m = line.match(/^"([^"]+)"\s*,?\s*(?:#\s*(.*))?$/);
    if (m) cronLines.push({ cron: m[1], comment: (m[2] || '').trim() });
  }

  const out = [`<!-- Auto-generated by scripts/regen-readme.js — do not edit by hand -->`, ``];
  out.push(`Total: **${cronLines.length} scheduled triggers**`);
  out.push(``);
  out.push(`| Cron (UTC)       | Description                                              |`);
  out.push(`|------------------|----------------------------------------------------------|`);
  for (const { cron, comment } of cronLines) {
    out.push(`| \`${cron.padEnd(15)}\` | ${(comment || '(no comment)').slice(0, 60).padEnd(60)} |`);
  }
  return out.join('\n');
}

function spliceSection(readme, marker, content) {
  const start = `<!-- ${marker}:START -->`;
  const end = `<!-- ${marker}:END -->`;
  const re = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (re.test(readme)) {
    return readme.replace(re, `${start}\n${content}\n${end}`);
  }
  // Marker missing — append a new section at end.
  return `${readme}\n\n## ${marker.replace(/_/g, ' ')}\n\n${start}\n${content}\n${end}\n`;
}

const readmePath = join(REPO, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
readme = spliceSection(readme, 'WORKERS', buildWorkerSection());
readme = spliceSection(readme, 'CRONS', buildCronSection());
writeFileSync(readmePath, readme);
console.log('README.md regenerated.');
